version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/webService
hooks:
  ApplicationStop:
    location: code-deploy/applicationStop.sh
    timeout: 300
    runas: ec2-user
  BeforeInstall:
    location: code-deploy/beforeInstall.sh
    timeout: 300
    runas: ec2-user
  ApplicationStart:
    location: code-deploy/applicationStart.sh
    timeout: 300
    runas: ec2-user